"""Astro CLI project scaffolding for save-gcp-local.

``save-gcp-local init-astro`` generates (or patches) all the files needed
so that ``astro dev start`` boots an Airflow that automatically intercepts
Dataproc operators and runs Spark jobs locally.

Generated / modified files:
  Dockerfile                         adds Java + Spark + save-gcp-local
  .env                               DPL_* config vars
  plugins/save_gcp_local_plugin.py   auto-loads patching at Airflow startup
  docker-compose.override.yml        local PostgreSQL + optional services
  include/local_connections.json     connection overrides for local services
"""

from __future__ import annotations

import logging
import os
from typing import Optional

log = logging.getLogger("save_gcp_local.astro")


# ================================================================ templates
# Stored as module-level strings to keep the package self-contained.

DOCKERFILE_APPEND = """\
# ── save-gcp-local: local Spark execution ─────────────────────────
# Install Java (required by Spark) and download Apache Spark.
USER root
RUN apt-get update && \\
    apt-get install -y --no-install-recommends openjdk-17-jre-headless procps && \\
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV SPARK_HOME=/opt/spark
ENV PATH="${SPARK_HOME}/bin:${PATH}"

ARG SPARK_VERSION=3.5.3
ARG HADOOP_VERSION=3
RUN curl -fsSL "https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" \\
    | tar -xz -C /opt && \\
    mv "/opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}" "${SPARK_HOME}"

# Install the framework.
RUN pip install --no-cache-dir "save-gcp-local[all]"
# Install early-patch so Airflow 2.x and 3.x both work.
RUN save-gcp-local install-airflow3 || true

USER astro
# ── end save-gcp-local ────────────────────────────────────────────
"""

PLUGIN_FILE = """\
# Auto-generated by: save-gcp-local init-astro
# This plugin patches Dataproc operators at Airflow startup so all Spark
# jobs run locally in the container instead of creating GCP clusters.
#
# Config is read from environment variables (DPL_*) — see .env file.

from save_gcp_local.airflow_plugin import *  # noqa: F401,F403

# Also set up local connection overrides so DAGs that reference
# google_cloud_default or database connections work without real credentials.
try:
    from save_gcp_local.connections import setup_local_connections
    setup_local_connections()
except Exception as _e:
    import logging
    logging.getLogger("save_gcp_local.plugin").warning(
        "[save-gcp-local] Connection setup failed: %s", _e,
    )
"""

ENV_FILE = """\
# ── save-gcp-local configuration ──────────────────────────────────
# Master switch (set false to let DAGs talk to real GCP)
DPL_ENABLED=true

# Runner: 'local' uses spark-submit inside this container (recommended
# for Astro); 'docker' would launch sibling containers (advanced).
DPL_RUNNER=local

# Spark is installed in the image at /opt/spark/bin/spark-submit
DPL_SPARK_SUBMIT_CMD=/opt/spark/bin/spark-submit
DPL_SPARK_MASTER=local[*]

# Directories — relative to the Airflow container filesystem.
# Astro mounts ./dags -> /usr/local/airflow/dags, ./include -> /usr/local/airflow/include
DPL_JOBS_DIR=/usr/local/airflow/include/jobs
DPL_DATA_DIR=/usr/local/airflow/include/data
DPL_OUTPUT_DIR=/usr/local/airflow/include/output

# Extra search roots for job files (comma-separated).
# Uncomment and add paths if jobs live outside include/jobs/.
# DPL_JOBS_PATH=/usr/local/airflow/dags

# Early patching (needed for Airflow 3.x, harmless on 2.x)
DPL_PATCH_EARLY=true

# Mock GCP project for connection stubs
DPL_GCP_PROJECT=local-dev-project

# Connection overrides file (optional — the plugin also applies defaults)
DPL_CONNECTIONS_FILE=/usr/local/airflow/include/local_connections.json

# Uncomment to patch custom operator subclasses:
# DPL_EXTRA_NOOP_OPERATORS=mypackage.operators.CustomCreateCluster
# DPL_EXTRA_SUBMIT_OPERATORS=mypackage.operators.CustomSubmitJob

# ── Airflow overrides useful for local dev ────────────────────────
# Hide example DAGs in the UI
AIRFLOW__CORE__LOAD_EXAMPLES=False
"""

COMPOSE_OVERRIDE = """\
# docker-compose.override.yml — generated by: save-gcp-local init-astro
#
# Adds local services that DAGs can connect to instead of cloud databases.
# These are available inside the Astro Docker network at their service name
# (e.g. host=local-postgres, port=5432).
#
# Uncomment / add services as needed.  Connection details should match the
# entries in include/local_connections.json.

version: "3"
services:
  # ── Local PostgreSQL (data warehouse stand-in) ──────────────────
  local-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: local_warehouse
    ports:
      - "5433:5432"
    volumes:
      - local-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localuser -d local_warehouse"]
      interval: 5s
      retries: 5

  # ── Local MySQL (uncomment if needed) ───────────────────────────
  # local-mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_DATABASE: local_warehouse
  #     MYSQL_USER: localuser
  #     MYSQL_PASSWORD: localpass
  #   ports:
  #     - "3307:3306"

  # ── Fake GCS server (uncomment for gs:// testing) ──────────────
  # fake-gcs:
  #   image: fsouza/fake-gcs-server
  #   command: ["-scheme", "http", "-port", "4443"]
  #   ports:
  #     - "4443:4443"

volumes:
  local-pg-data:
"""

CONNECTIONS_JSON = """\
{
  "google_cloud_default": {
    "conn_type": "google_cloud_platform",
    "extra": "{\\"project\\": \\"local-dev-project\\", \\"num_retries\\": 0}",
    "description": "[save-gcp-local] Mock GCP connection — Dataproc operators are patched to no-op"
  },
  "local_postgres": {
    "conn_type": "postgres",
    "host": "local-postgres",
    "port": 5432,
    "login": "localuser",
    "password": "localpass",
    "schema": "local_warehouse",
    "description": "[save-gcp-local] Local PostgreSQL for dev/test"
  }
}
"""


# ============================================================ scaffolding

def _write_if_missing(path: str, content: str, force: bool = False) -> str:
    """Write content to path if the file doesn't exist. Returns status."""
    if os.path.exists(path) and not force:
        return "exists"
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return "created"


def _append_if_missing(path: str, marker: str, content: str) -> str:
    """Append content to path if marker string is not already present."""
    if not os.path.exists(path):
        return "not found"
    with open(path) as f:
        existing = f.read()
    if marker in existing:
        return "already patched"
    with open(path, "a") as f:
        f.write("\n" + content)
    return "patched"


def scaffold_astro_project(
    project_dir: str,
    force: bool = False,
    skip_compose: bool = False,
) -> dict:
    """Generate all save-gcp-local integration files for an Astro project.

    Args:
        project_dir: Root of the Astro project (where Dockerfile lives).
        force:       Overwrite existing generated files.
        skip_compose: Don't generate docker-compose.override.yml.

    Returns:
        Dict of {filename: status} for each file processed.
    """
    results = {}

    # 1. Patch Dockerfile
    dockerfile = os.path.join(project_dir, "Dockerfile")
    marker = "save-gcp-local"
    status = _append_if_missing(dockerfile, marker, DOCKERFILE_APPEND)
    results["Dockerfile"] = status

    # 2. Plugin file
    plugin_dir = os.path.join(project_dir, "plugins")
    plugin_path = os.path.join(plugin_dir, "save_gcp_local_plugin.py")
    results["plugins/save_gcp_local_plugin.py"] = _write_if_missing(plugin_path, PLUGIN_FILE, force)

    # 3. .env file — append, don't overwrite
    env_path = os.path.join(project_dir, ".env")
    status = _append_if_missing(env_path, "DPL_ENABLED", ENV_FILE)
    if status == "not found":
        _write_if_missing(env_path, ENV_FILE, force=True)
        status = "created"
    results[".env"] = status

    # 4. docker-compose.override.yml
    if not skip_compose:
        compose_path = os.path.join(project_dir, "docker-compose.override.yml")
        results["docker-compose.override.yml"] = _write_if_missing(compose_path, COMPOSE_OVERRIDE, force)

    # 5. include/ directories and connections file
    for d in ("include/jobs", "include/data", "include/output"):
        full = os.path.join(project_dir, d)
        os.makedirs(full, exist_ok=True)
        gitkeep = os.path.join(full, ".gitkeep")
        if not os.path.exists(gitkeep):
            with open(gitkeep, "w") as f:
                f.write("")

    conn_path = os.path.join(project_dir, "include", "local_connections.json")
    results["include/local_connections.json"] = _write_if_missing(conn_path, CONNECTIONS_JSON, force)

    # 6. Add save-gcp-local to requirements.txt if not already there
    req_path = os.path.join(project_dir, "requirements.txt")
    if os.path.exists(req_path):
        with open(req_path) as f:
            req_content = f.read()
        if "save-gcp-local" not in req_content:
            with open(req_path, "a") as f:
                f.write("\nsave-gcp-local[all]\n")
            results["requirements.txt"] = "updated"
        else:
            results["requirements.txt"] = "already present"
    else:
        results["requirements.txt"] = "not found"

    return results
