"""Astro CLI project scaffolding for save-gcp-local.

``save-gcp-local init-astro`` generates (or patches) all the files needed
so that ``astro dev start`` boots an Airflow that automatically intercepts
Dataproc operators and runs Spark jobs locally.

Generated / modified files:
  Dockerfile                         adds Java + Spark + connector JARs + save-gcp-local
  .env                               DPL_* config vars
  plugins/save_gcp_local_plugin.py   auto-loads patching at Airflow startup
  docker-compose.override.yml        local PostgreSQL, Hive, OpenSearch, SQL Server
  include/local_connections.json     connection overrides for local services
  include/local_variables.json       Airflow Variable overrides for local dev
"""

from __future__ import annotations

import logging
import os
from typing import Optional

log = logging.getLogger("save_gcp_local.astro")


# ================================================================ templates
# Stored as module-level strings to keep the package self-contained.

DOCKERFILE_APPEND = """\
# ── save-gcp-local: local Spark execution ─────────────────────────
# Install Java (required by Spark) and download Apache Spark.
USER root
RUN apt-get update && \\
    apt-get install -y --no-install-recommends openjdk-17-jre-headless procps && \\
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV SPARK_HOME=/opt/spark
ENV PATH="${SPARK_HOME}/bin:${PATH}"

ARG SPARK_VERSION=3.5.3
ARG HADOOP_VERSION=3
RUN curl -fsSL "https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" \\
    | tar -xz -C /opt && \\
    mv "/opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}" "${SPARK_HOME}"

# Download connector JARs so Spark can talk to Hive, PostgreSQL, SQL Server,
# MySQL, and OpenSearch out of the box.  They go into $SPARK_HOME/jars/ so
# Spark auto-classpaths them — no --jars flags needed.
RUN curl -fsSL -o ${SPARK_HOME}/jars/postgresql-42.7.1.jar \\
      "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.1/postgresql-42.7.1.jar" && \\
    curl -fsSL -o ${SPARK_HOME}/jars/mssql-jdbc-12.4.2.jre11.jar \\
      "https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.4.2.jre11/mssql-jdbc-12.4.2.jre11.jar" && \\
    curl -fsSL -o ${SPARK_HOME}/jars/mysql-connector-j-8.3.0.jar \\
      "https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.3.0/mysql-connector-j-8.3.0.jar"

# Install the framework.
RUN pip install --no-cache-dir "save-gcp-local[all]"
# Install early-patch so Airflow 2.x and 3.x both work.
RUN save-gcp-local install-airflow3 || true

USER astro
# ── end save-gcp-local ────────────────────────────────────────────
"""

PLUGIN_FILE = """\
# Auto-generated by: save-gcp-local init-astro
# This plugin patches Dataproc operators at Airflow startup so all Spark
# jobs run locally in the container instead of creating GCP clusters.
#
# Config is read from environment variables (DPL_*) — see .env file.

from save_gcp_local.airflow_plugin import *  # noqa: F401,F403

# Also set up local connection overrides so DAGs that reference
# google_cloud_default or database connections work without real credentials.
try:
    from save_gcp_local.connections import setup_local_connections
    setup_local_connections()
except Exception as _e:
    import logging
    logging.getLogger("save_gcp_local.plugin").warning(
        "[save-gcp-local] Connection setup failed: %s", _e,
    )

# Set up Airflow Variables from local config so Variable.get() works.
try:
    from save_gcp_local.variables import setup_local_variables
    setup_local_variables()
except Exception as _e:
    import logging
    logging.getLogger("save_gcp_local.plugin").debug(
        "[save-gcp-local] Variable setup skipped: %s", _e,
    )
"""

ENV_FILE = """\
# ── save-gcp-local configuration ──────────────────────────────────
# Master switch (set false to let DAGs talk to real GCP)
DPL_ENABLED=true

# Runner: 'local' uses spark-submit inside this container (recommended
# for Astro); 'docker' would launch sibling containers (advanced).
DPL_RUNNER=local

# Container engine for the 'docker' runner (auto-detects docker/podman).
# DPL_CONTAINER_ENGINE=auto

# Spark is installed in the image at /opt/spark/bin/spark-submit
DPL_SPARK_SUBMIT_CMD=/opt/spark/bin/spark-submit
DPL_SPARK_MASTER=local[*]

# Directories — relative to the Airflow container filesystem.
# Astro mounts ./dags -> /usr/local/airflow/dags, ./include -> /usr/local/airflow/include
DPL_JOBS_DIR=/usr/local/airflow/include/jobs
DPL_DATA_DIR=/usr/local/airflow/include/data
DPL_OUTPUT_DIR=/usr/local/airflow/include/output

# Extra search roots for job files (comma-separated).
# Uncomment and add paths if jobs live outside include/jobs/.
# DPL_JOBS_PATH=/usr/local/airflow/dags

# Spark configuration (comma-separated key=value pairs).
# Hive metastore URI is pre-configured for the local Hive service.
DPL_SPARK_CONF=spark.hadoop.hive.metastore.uris=thrift://local-hive:9083,spark.sql.catalogImplementation=hive

# Early patching (needed for Airflow 3.x, harmless on 2.x)
DPL_PATCH_EARLY=true

# Mock GCP project for connection stubs
DPL_GCP_PROJECT=local-dev-project

# Connection overrides file
DPL_CONNECTIONS_FILE=/usr/local/airflow/include/local_connections.json

# Variable overrides file (Airflow Variables for DAGs)
DPL_VARIABLES_FILE=/usr/local/airflow/include/local_variables.json

# Uncomment to patch custom operator subclasses:
# DPL_EXTRA_NOOP_OPERATORS=mypackage.operators.CustomCreateCluster
# DPL_EXTRA_SUBMIT_OPERATORS=mypackage.operators.CustomSubmitJob

# Uncomment to add extra connector JARs (outside $SPARK_HOME/jars/):
# DPL_CONNECTOR_JARS=/path/to/custom-connector.jar,/path/to/another.jar

# ── Airflow overrides useful for local dev ────────────────────────
# Hide example DAGs in the UI
AIRFLOW__CORE__LOAD_EXAMPLES=False
"""

COMPOSE_OVERRIDE = """\
# docker-compose.override.yml — generated by: save-gcp-local init-astro
#
# Local services that DAGs can connect to instead of cloud databases.
# These are available inside the Astro Docker network at their service name.
# Connection details match the entries in include/local_connections.json.
#
# Comment out services you don't need to save resources.

version: "3"
services:
  # ── Local PostgreSQL (data warehouse stand-in) ──────────────────
  local-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: local_warehouse
    ports:
      - "5433:5432"
    volumes:
      - local-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localuser -d local_warehouse"]
      interval: 5s
      retries: 5

  # ── Local Hive Metastore (for Hive table access from Spark) ────
  local-hive:
    image: apache/hive:4.0.0
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: derby
    ports:
      - "9083:9083"
    volumes:
      - local-hive-data:/opt/hive/data/warehouse

  # ── Local OpenSearch ──────────────────────────────────────────────
  local-opensearch:
    image: opensearchproject/opensearch:2.17.1
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "LocalDev#123"
    ports:
      - "9200:9200"
    volumes:
      - local-os-data:/usr/share/opensearch/data

  # ── Local SQL Server (Azure DB equivalent) ────────────────────────
  local-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LocalPass#123"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - local-mssql-data:/var/opt/mssql

  # ── Local MySQL (uncomment if needed) ───────────────────────────
  # local-mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_DATABASE: local_warehouse
  #     MYSQL_USER: localuser
  #     MYSQL_PASSWORD: localpass
  #   ports:
  #     - "3307:3306"

  # ── Fake GCS server (uncomment for gs:// testing) ──────────────
  # fake-gcs:
  #   image: fsouza/fake-gcs-server
  #   command: ["-scheme", "http", "-port", "4443"]
  #   ports:
  #     - "4443:4443"

volumes:
  local-pg-data:
  local-hive-data:
  local-os-data:
  local-mssql-data:
"""

CONNECTIONS_JSON = """\
{
  "google_cloud_default": {
    "conn_type": "google_cloud_platform",
    "extra": "{\\"project\\": \\"local-dev-project\\", \\"num_retries\\": 0}",
    "description": "[save-gcp-local] Mock GCP connection — Dataproc operators are patched"
  },
  "local_postgres": {
    "conn_type": "postgres",
    "host": "local-postgres",
    "port": 5432,
    "login": "localuser",
    "password": "localpass",
    "schema": "local_warehouse",
    "description": "[save-gcp-local] Local PostgreSQL for dev/test"
  },
  "hive_default": {
    "conn_type": "hiveserver2",
    "host": "local-hive",
    "port": 9083,
    "login": "hive",
    "schema": "default",
    "description": "[save-gcp-local] Local Hive metastore for dev/test"
  },
  "opensearch_default": {
    "conn_type": "http",
    "host": "local-opensearch",
    "port": 9200,
    "description": "[save-gcp-local] Local OpenSearch for dev/test"
  },
  "mssql_default": {
    "conn_type": "mssql",
    "host": "local-mssql",
    "port": 1433,
    "login": "sa",
    "password": "LocalPass#123",
    "schema": "master",
    "description": "[save-gcp-local] Local SQL Server (Azure DB equivalent) for dev/test"
  }
}
"""

VARIABLES_JSON = """\
{
  "hive_metastore_uri": "thrift://local-hive:9083",
  "opensearch_host": "http://local-opensearch:9200",
  "mssql_host": "local-mssql",
  "mssql_port": "1433",
  "gcp_project": "local-dev-project",
  "environment": "local"
}
"""


# ============================================================ scaffolding

def _write_if_missing(path: str, content: str, force: bool = False) -> str:
    """Write content to path if the file doesn't exist. Returns status."""
    if os.path.exists(path) and not force:
        return "exists"
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return "created"


def _append_if_missing(path: str, marker: str, content: str) -> str:
    """Append content to path if marker string is not already present."""
    if not os.path.exists(path):
        return "not found"
    with open(path) as f:
        existing = f.read()
    if marker in existing:
        return "already patched"
    with open(path, "a") as f:
        f.write("\n" + content)
    return "patched"


def scaffold_astro_project(
    project_dir: str,
    force: bool = False,
    skip_compose: bool = False,
    engine: str = "auto",
) -> dict:
    """Generate all save-gcp-local integration files for an Astro project.

    Args:
        project_dir: Root of the Astro project (where Dockerfile lives).
        force:       Overwrite existing generated files.
        skip_compose: Don't generate docker-compose.override.yml.
        engine:      Container engine hint ('auto', 'docker', 'podman').

    Returns:
        Dict of {filename: status} for each file processed.
    """
    results = {}

    # 1. Patch Dockerfile
    dockerfile = os.path.join(project_dir, "Dockerfile")
    marker = "save-gcp-local"
    status = _append_if_missing(dockerfile, marker, DOCKERFILE_APPEND)
    results["Dockerfile"] = status

    # 2. Plugin file
    plugin_dir = os.path.join(project_dir, "plugins")
    plugin_path = os.path.join(plugin_dir, "save_gcp_local_plugin.py")
    results["plugins/save_gcp_local_plugin.py"] = _write_if_missing(plugin_path, PLUGIN_FILE, force)

    # 3. .env file — append, don't overwrite; inject engine choice
    env_content = ENV_FILE
    if engine != "auto":
        env_content = env_content.replace(
            "# DPL_CONTAINER_ENGINE=auto",
            f"DPL_CONTAINER_ENGINE={engine}",
        )
    env_path = os.path.join(project_dir, ".env")
    status = _append_if_missing(env_path, "DPL_ENABLED", env_content)
    if status == "not found":
        _write_if_missing(env_path, env_content, force=True)
        status = "created"
    results[".env"] = status

    # 4. docker-compose.override.yml
    if not skip_compose:
        compose_path = os.path.join(project_dir, "docker-compose.override.yml")
        results["docker-compose.override.yml"] = _write_if_missing(compose_path, COMPOSE_OVERRIDE, force)

    # 5. include/ directories, connections file, and variables file
    for d in ("include/jobs", "include/data", "include/output"):
        full = os.path.join(project_dir, d)
        os.makedirs(full, exist_ok=True)
        gitkeep = os.path.join(full, ".gitkeep")
        if not os.path.exists(gitkeep):
            with open(gitkeep, "w") as f:
                f.write("")

    conn_path = os.path.join(project_dir, "include", "local_connections.json")
    results["include/local_connections.json"] = _write_if_missing(conn_path, CONNECTIONS_JSON, force)

    vars_path = os.path.join(project_dir, "include", "local_variables.json")
    results["include/local_variables.json"] = _write_if_missing(vars_path, VARIABLES_JSON, force)

    # 6. Add save-gcp-local to requirements.txt if not already there
    req_path = os.path.join(project_dir, "requirements.txt")
    if os.path.exists(req_path):
        with open(req_path) as f:
            req_content = f.read()
        if "save-gcp-local" not in req_content:
            with open(req_path, "a") as f:
                f.write("\nsave-gcp-local[all]\n")
            results["requirements.txt"] = "updated"
        else:
            results["requirements.txt"] = "already present"
    else:
        results["requirements.txt"] = "not found"

    return results
